from __future__ import annotations

import hashlib


def round6_contract_sha256(
    *,
    branch_name: str,
    branch_id: str,
    branch_uid: str,
    branch_create_time: str,
    endpoint_name: str,
    endpoint_id: str,
    endpoint_uid: str,
    endpoint_create_time: str,
    database_resource_name: str,
    database_resource_id: str,
    postgres_database: str,
    source_schema: str,
    source_table: str,
    source_table_oid: int,
    cdf_config_name: str,
    cdf_config_id: str,
    cdf_config_create_time: str,
    cdf_status_name: str,
    cdf_status_id: str,
    cdf_status_create_time: str,
    destination_catalog: str,
    destination_schema: str,
    destination_schema_id: str,
    destination_table_full_name: str,
    destination_table_id: str,
    baseline_order_id: str,
    baseline_proof_nonce: str,
    baseline_sku: str,
    baseline_store: str,
    baseline_quantity: int,
    baseline_total_cents: int,
    baseline_status: str,
) -> str:
    """Hash every immutable identity used by the Round 6 proof."""

    values = (
        branch_name,
        branch_id,
        branch_uid,
        branch_create_time,
        endpoint_name,
        endpoint_id,
        endpoint_uid,
        endpoint_create_time,
        database_resource_name,
        database_resource_id,
        postgres_database,
        source_schema,
        source_table,
        str(source_table_oid),
        cdf_config_name,
        cdf_config_id,
        cdf_config_create_time,
        cdf_status_name,
        cdf_status_id,
        cdf_status_create_time,
        destination_catalog,
        destination_schema,
        destination_schema_id,
        destination_table_full_name,
        destination_table_id,
        baseline_order_id,
        baseline_proof_nonce,
        baseline_sku,
        baseline_store,
        str(baseline_quantity),
        str(baseline_total_cents),
        baseline_status,
    )
    return hashlib.sha256("\0".join(values).encode("utf-8")).hexdigest()
