/**
 * THE LONG WALK BACK — the end-title cue, ported from the standalone credits
 * deliverable that the user heard and approved.
 *
 * The score is unchanged: 40 bars of 4/4 at 110 BPM, 87.27 s of music plus a
 * 0.45 s ring-out. Two pulse voices switching between 12.5% / 25% / 50% duty,
 * one triangle on the bass, one noise channel carrying every drum as a real
 * 15-bit LFSR at a different timer period. Never more than four voices sound
 * at once, and nothing here is a sine, a sawtooth or a filter.
 *
 * D minor -> B-flat major -> F major -> D MAJOR -> one bar of D minor -> D
 * major. Bars 29-36 are the payoff: FINAL BELL's D-A-C-F hook, four sixteenths
 * in the title theme, returns as half notes across two bars and translated
 * into the parallel major as D-A-C#-F#, sustained on pulse 1 while pulse 2
 * climbs above it. Bar 39 quotes the title theme's closing D-major arpeggio;
 * bar 40 lands the chord.
 *
 * WHAT CHANGED IN THE PORT, and nothing else did:
 *   - The cue is planned into the flat CueEvent list that audio.ts's shared
 *     runtime already plays for the title score and the six round cues, rather
 *     than carrying its own scheduler, its own PeriodicWave cache and its own
 *     LFSR. Three schedulers became one.
 *   - The note tail is the runtime's: a 3.5 ms linear ramp to zero off a -16 dB
 *     shelf, instead of an exponential run to -80 dB across the back of the
 *     gate. Same lengths, same onsets, no hole in front of the bar line.
 *   - Bar 40's bell is a LANDMARK, not an event. The roll strikes the bell
 *     itself (credits.tsx), so the cue exposes CREDITS_THEME_BELL_SECONDS and
 *     leaves the noise channel empty under it rather than striking a second
 *     one. Two bells 14 s apart would be worse than one in the right place.
 *
 * Generated by lakebase-anti-demo-scratch/credits/audio/integration/generate.mjs.
 * The score data below is byte-identical to credits-theme.audio.ts; edit the
 * scratch arrangement and regenerate rather than editing this file.
 */

export type CreditsChannel = 'pulse1' | 'pulse2' | 'triangle' | 'noise'

/** The shape audio.ts's cue runtime consumes. Structural, not imported. */
export interface CreditsEvent {
  readonly channel: CreditsChannel
  readonly kind: 'note' | 'noise'
  readonly time: number
  readonly duration: number
  readonly gain: number
  readonly frequency?: number
  readonly duty?: number
  readonly attack?: number
  readonly sustain?: number
  readonly period?: number
  readonly rateFrom?: number
}

export interface CreditsPlan {
  readonly introDuration: number
  readonly loopDuration: number
  readonly introEvents: readonly CreditsEvent[]
  readonly loopEvents: readonly CreditsEvent[]
  /** Seconds from the cue's first beat to bar 40's downbeat. */
  readonly bellTime: number
}

/**
 * Chosen to sit AT the title score, not at the rounds.
 *
 * The rounds are at 0.1 because somebody is talking over them. Nobody talks
 * over the credits: like the title screen it plays to a room that is watching,
 * so it belongs at the title screen's level rather than under it.
 *
 * The number is SMALLER than the title's 0.18 because the cue is denser: 1091
 * events over 88 s against the title score's 944 over 77 s, and where the
 * title loop holds one steady weight this one is written to swell. Measured
 * off the live graph over both whole forms, the standalone's 0.22 ran 4.1 dB
 * hot against the title score. 0.14 matches it. Opening the roll from the
 * title screen is then not a level change, and the piece's own dynamic curve
 * still does what it was written to do: half-lit at bar 1, biggest at bar 40.
 */
export const CREDITS_THEME_VOLUME = 0.14

type CreditsNoteStep = number | null
type CreditsDrumStep = 'K' | 'k' | 'S' | 's' | 'H' | 'h' | 'r' | null

interface CreditsVoice {
  duty: number
  gate: number
  attack: number
  sustain: number
  volume: number
}

interface CreditsSection {
  id: string
  label: string
  startBar: number
  bars: number
  pulse1: CreditsVoice
  pulse2: CreditsVoice
  triangle: CreditsVoice
}

type CreditsPitchedChannel = 'pulse1' | 'pulse2' | 'triangle'

const N = null

const C3 = 130.81; const D3 = 146.83; const Eb3 = 155.56; const E3 = 164.81
const F3 = 174.61; const Fs3 = 185; const G3 = 196; const A3 = 220
const Bb3 = 233.08; const B3 = 246.94
const C4 = 261.63; const Cs4 = 277.18; const D4 = 293.66; const Eb4 = 311.13
const E4 = 329.63; const F4 = 349.23; const Fs4 = 369.99; const G4 = 392
const A4 = 440; const Bb4 = 466.16
const C5 = 523.25; const Cs5 = 554.37; const D5 = 587.33; const Eb5 = 622.25
const E5 = 659.25; const F5 = 698.46; const Fs5 = 739.99; const G5 = 783.99
const A5 = 880; const Bb5 = 932.33; const B5 = 987.77
const Cs6 = 1108.73; const D6 = 1174.66

/** Join bars into one flat step list. Scores are written a bar at a time. */
function phrase<T>(...sections: ReadonlyArray<readonly T[]>): readonly T[] {
  return sections.flat()
}

const CREDITS_STEPS_PER_BAR = 16
const CREDITS_BARS = 40
const CREDITS_BPM = 110
const CREDITS_STEP_SECONDS = 60 / CREDITS_BPM / 4
const CREDITS_BAR_SECONDS = CREDITS_STEP_SECONDS * CREDITS_STEPS_PER_BAR
const CREDITS_MUSIC_SECONDS = CREDITS_BARS * CREDITS_BAR_SECONDS
const CREDITS_DURATION = CREDITS_MUSIC_SECONDS + 0.45
const CREDITS_FINAL_STEP = (CREDITS_BARS - 1) * CREDITS_STEPS_PER_BAR

// ---------------------------------------------------------------------------
// PULSE 1 — lead. 12.5% in the intro, 50% for every statement, and the
// sustained augmented title-theme hook across bars 29-36.
// ---------------------------------------------------------------------------
const CREDITS_PULSE_1: readonly CreditsNoteStep[] = phrase(
  // 1-4 Intro. D minor, half-lit; the credits theme's opening cell alone.
  [N, N, N, N, N, N, N, N, A4, N, N, N, D5, N, N, N],
  [F5, N, N, N, E5, N, N, N, D5, N, N, N, N, N, N, N],
  [Bb4, N, N, N, D5, N, N, N, G4, N, N, N, Bb4, N, D5, N],
  [Cs5, N, N, N, E5, N, N, N, A4, N, Cs5, N, E5, N, G5, N],
  // 5-12 A. First full statement: broad quarters, an arch to A5, A-major cadence.
  [A4, N, N, N, D5, N, N, N, F5, N, N, N, E5, N, N, N],
  [F5, N, N, E5, D5, N, N, N, C5, N, D5, N, F5, N, N, N],
  [A4, N, N, N, C5, N, N, N, F5, N, N, N, E5, N, D5, N],
  [C5, N, N, N, E5, N, N, G5, E5, N, D5, N, C5, N, N, N],
  [D5, N, N, N, F5, N, N, N, A5, N, N, G5, F5, N, N, N],
  [G5, N, N, N, F5, N, E5, N, D5, N, N, N, Bb4, N, C5, N],
  [Cs5, N, N, N, E5, N, N, N, A4, N, Cs5, N, E5, N, G5, N],
  [F5, N, N, N, E5, N, D5, N, A4, N, N, N, D5, N, N, N],
  // 13-20 B. Hands the tune to pulse 2 and drops to 12.5% for a low off-beat
  // arpeggio beneath it — the contrast is timbral as well as harmonic.
  [N, N, F4, N, N, N, Bb4, N, N, N, F4, N, N, N, D5, N],
  [N, N, A4, N, N, N, C5, N, N, N, A4, N, N, N, F4, N],
  [N, N, Bb4, N, N, N, D5, N, N, N, Bb4, N, N, N, G4, N],
  [N, N, G4, N, N, N, Bb4, N, N, N, G4, N, N, N, Eb4, N],
  [N, N, F4, N, N, N, Bb4, N, N, N, D5, N, N, N, Bb4, N],
  [N, N, Bb4, N, N, N, D5, N, N, N, G4, N, N, N, Bb4, N],
  [N, N, G4, N, N, N, Bb4, N, N, N, Eb5, N, N, N, Bb4, N],
  [N, N, G4, N, N, N, Bb4, N, N, N, E4, N, N, N, G4, N],
  // 21-28 Development. F major, register climbing, then two bars of A7 held
  // open as the door into D major.
  [F5, N, N, N, A5, N, N, G5, F5, N, E5, N, D5, N, C5, N],
  [C5, N, E5, N, G5, N, N, F5, E5, N, D5, N, C5, N, D5, N],
  [D5, N, F5, N, Bb5, N, N, A5, G5, N, F5, N, D5, N, F5, N],
  [G5, N, N, F5, E5, N, G5, N, C5, N, E5, N, G5, N, A5, N],
  [Bb5, N, N, A5, G5, N, D5, N, G5, N, Bb5, N, A5, N, G5, N],
  [D5, N, F5, N, Bb5, N, A5, N, G5, N, F5, N, E5, N, D5, N],
  [Cs5, N, E5, N, A5, N, N, G5, E5, N, Cs5, N, E5, N, G5, N],
  [A5, N, N, G5, E5, N, Cs5, N, A4, N, Cs5, N, E5, N, G5, A5],
  // 29-36 RECAP — THE CALLBACK. FINAL BELL states D-A-C-F as four sixteenths
  // inside half a bar. Here the same four pitches are half notes spanning two
  // bars, raised into the parallel major: D-A-C#-F#. Bars 31-32 answer with the
  // title theme's own F-E-C#-D tail, likewise augmented. Bars 33-36 restate the
  // whole thing note for note while pulse 2 rises above it into a descant.
  [D5, N, N, N, N, N, N, N, A4, N, N, N, N, N, N, N],
  [Cs5, N, N, N, N, N, N, N, Fs5, N, N, N, N, N, N, N],
  [Fs5, N, N, N, N, N, N, N, E5, N, N, N, N, N, N, N],
  [Cs5, N, N, N, N, N, N, N, D5, N, N, N, N, N, N, N],
  [D5, N, N, N, N, N, N, N, A4, N, N, N, N, N, N, N],
  [Cs5, N, N, N, N, N, N, N, Fs5, N, N, N, N, N, N, N],
  [Fs5, N, N, N, N, N, N, N, E5, N, N, N, N, N, N, N],
  [Cs5, N, N, N, N, N, N, N, D5, N, N, N, N, N, N, N],
  // 37-40 Coda. The suspended D resolves into D MINOR for one bar — the last
  // look back — then B-flat to A major, then FINAL BELL's own closing D-major
  // arpeggio shape, then the chord that ends the show.
  [D5, N, N, N, F5, N, N, N, A4, N, N, N, D5, N, N, N],
  [Bb4, N, N, N, D5, N, N, N, Cs5, N, N, N, E5, N, G5, N],
  [D5, Fs5, A5, N, Fs5, E5, D5, N, A4, D5, Fs5, A5, D6, N, N, N],
  [D6, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
)

// ---------------------------------------------------------------------------
// PULSE 2 — 25% duty throughout. Sustained harmony, then an inner voice, then
// the B-section melody, then the descant that crowns the recap.
// ---------------------------------------------------------------------------
const CREDITS_PULSE_2: readonly CreditsNoteStep[] = phrase(
  [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
  [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
  [G4, N, N, N, N, N, N, N, Bb4, N, N, N, N, N, N, N],
  [E4, N, N, N, N, N, N, N, A4, N, N, N, N, N, N, N],
  [F4, N, N, N, N, N, N, N, A4, N, N, N, N, N, N, N],
  [D4, N, N, N, N, N, N, N, F4, N, N, N, N, N, N, N],
  [C4, N, N, N, N, N, N, N, A4, N, N, N, N, N, N, N],
  [E4, N, N, N, N, N, N, N, G4, N, N, N, N, N, N, N],
  [A4, N, N, N, D5, N, N, N, F5, N, N, E5, D5, N, N, N],
  [D5, N, N, N, Bb4, N, C5, N, Bb4, N, N, N, G4, N, A4, N],
  [A4, N, N, N, Cs5, N, N, N, E4, N, A4, N, Cs5, N, E5, N],
  [D5, N, N, N, Cs5, N, A4, N, F4, N, N, N, A4, N, C5, D5],
  // 13-20 B. Flowing eighths in B-flat major against A's broad quarters.
  [F4, N, Bb4, N, D5, N, N, N, C5, N, Bb4, N, D5, N, N, N],
  [C5, N, A4, N, F4, N, A4, N, C5, N, D5, N, C5, N, N, N],
  [Bb4, N, D5, N, G5, N, N, F5, D5, N, Bb4, N, C5, N, D5, N],
  [Eb5, N, N, D5, C5, N, Bb4, N, G4, N, Bb4, N, C5, N, D5, N],
  [F5, N, N, N, D5, N, F5, N, Bb4, N, D5, N, F5, N, G5, N],
  [G5, N, N, F5, D5, N, N, Bb4, D5, N, F5, N, G5, N, N, N],
  [G5, N, N, Eb5, F5, N, G5, N, Bb5, N, N, A5, G5, N, F5, N],
  [E5, N, N, D5, C5, N, Bb4, N, G4, N, Bb4, N, C5, N, E5, N],
  // 21-28 Development accompaniment.
  [A4, N, C5, N, F4, N, A4, N, C5, N, A4, N, F4, N, A4, N],
  [E4, N, G4, N, C5, N, G4, N, F4, N, A4, N, D5, N, A4, N],
  [F4, N, Bb4, N, D5, N, Bb4, N, F4, N, D5, N, Bb4, N, F4, N],
  [E4, N, G4, N, C5, N, G4, N, E4, N, G4, N, C5, N, E5, N],
  [G4, N, Bb4, N, D5, N, Bb4, N, G4, N, D5, N, Bb4, N, G4, N],
  [F4, N, Bb4, N, D5, N, Bb4, N, F4, N, D5, N, Bb4, N, F4, N],
  [E4, N, A4, N, Cs5, N, A4, N, E4, N, G4, N, A4, N, Cs5, N],
  [A4, N, Cs5, N, E5, N, Cs5, N, A4, N, G4, N, E4, N, A4, Cs5],
  // 29-32 Recap statement one: deliberately BELOW the hook, in sixths and
  // thirds, so the augmented melody is unmistakably the top line. The back
  // half of bar 32 is a scalar lift that hands the register upward.
  [Fs4, N, N, N, N, N, N, N, A4, N, N, N, N, N, N, N],
  [E4, N, N, N, N, N, N, N, A4, N, N, N, N, N, N, N],
  [A4, N, N, N, N, N, N, N, Cs5, N, N, N, N, N, N, N],
  [E4, N, N, N, G4, N, N, N, A4, N, Cs5, N, E5, N, Fs5, A5],
  // 33-36 Recap statement two: the same hook underneath, pulse 2 now ABOVE it
  // in the A5-D6 octave. This is the countermelody the whole cue was built for.
  [A5, N, N, Fs5, D6, N, N, A5, Fs5, N, A5, N, B5, N, D6, N],
  [Cs6, N, N, B5, A5, N, E5, N, Fs5, N, A5, N, D6, N, N, N],
  [B5, N, N, A5, G5, N, B5, N, Cs6, N, N, B5, A5, N, Cs6, N],
  [D6, N, N, Cs6, B5, N, A5, N, Fs5, N, A5, N, Cs6, N, E5, G5],
  // 37-40 Coda.
  [F4, N, N, N, N, N, N, N, D4, N, N, N, N, N, N, N],
  [D5, N, N, N, Bb4, N, N, N, A4, N, N, N, Cs5, N, E5, N],
  [Fs4, A4, D5, N, A4, G4, Fs4, N, D4, Fs4, A4, D5, Fs5, N, N, N],
  [Fs5, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
)

// ---------------------------------------------------------------------------
// TRIANGLE — bass, every bar. Whole notes in the intro, halves through A,
// walking eighths from bar 9 on.
// ---------------------------------------------------------------------------
const CREDITS_TRIANGLE: readonly CreditsNoteStep[] = phrase(
  [D3, N, N, N, N, N, N, N, A3, N, N, N, N, N, N, N],
  [F3, N, N, N, N, N, N, N, Bb3, N, N, N, N, N, N, N],
  [G3, N, N, N, N, N, N, N, D3, N, N, N, N, N, N, N],
  [A3, N, N, N, N, N, N, N, E3, N, N, N, N, N, N, N],
  [D3, N, N, N, N, N, N, N, A3, N, N, N, N, N, N, N],
  [Bb3, N, N, N, N, N, N, N, F3, N, N, N, N, N, N, N],
  [F3, N, N, N, C3, N, N, N, F3, N, N, N, A3, N, N, N],
  [C3, N, N, N, G3, N, N, N, C3, N, N, N, E3, N, G3, N],
  [D3, N, A3, N, D3, N, F3, N, A3, N, F3, N, D3, N, A3, N],
  [Bb3, N, F3, N, Bb3, N, D3, N, G3, N, D3, N, G3, N, Bb3, N],
  [A3, N, E3, N, A3, N, Cs4, N, E3, N, A3, N, G3, N, E3, N],
  [D3, N, A3, N, D3, N, F3, N, A3, N, D3, N, F3, N, A3, N],
  [Bb3, N, N, N, F3, N, N, N, Bb3, N, N, N, D3, N, N, N],
  [F3, N, N, N, C3, N, N, N, F3, N, N, N, A3, N, N, N],
  [G3, N, N, N, D3, N, N, N, G3, N, N, N, Bb3, N, N, N],
  [Eb3, N, N, N, Bb3, N, N, N, Eb3, N, N, N, G3, N, N, N],
  [Bb3, N, F3, N, Bb3, N, D3, N, F3, N, Bb3, N, D3, N, F3, N],
  [G3, N, D3, N, G3, N, Bb3, N, D3, N, G3, N, Bb3, N, D3, N],
  [Eb3, N, Bb3, N, Eb3, N, G3, N, Bb3, N, G3, N, Eb3, N, G3, N],
  [C3, N, G3, N, C3, N, E3, N, G3, N, Bb3, N, E3, N, G3, N],
  [F3, N, C3, N, F3, N, A3, N, C3, N, A3, N, F3, N, C3, N],
  [C3, N, G3, N, C3, N, E3, N, D3, N, A3, N, D3, N, F3, N],
  [Bb3, N, F3, N, Bb3, N, D3, N, F3, N, D3, N, Bb3, N, F3, N],
  [C3, N, G3, N, C3, N, E3, N, G3, N, E3, N, C3, N, G3, N],
  [G3, N, D3, N, G3, N, Bb3, N, D3, N, Bb3, N, G3, N, D3, N],
  [Bb3, N, F3, N, Bb3, N, D3, N, F3, N, D3, N, Bb3, N, F3, N],
  [A3, N, E3, N, A3, N, Cs4, N, E3, N, Cs4, N, A3, N, G3, N],
  [A3, N, E3, N, A3, N, G3, N, E3, N, Cs4, N, E3, N, A3, Cs4],
  [D3, N, A3, N, D3, N, Fs3, N, B3, N, Fs3, N, B3, N, A3, N],
  [A3, N, E3, N, A3, N, Cs4, N, D3, N, A3, N, D3, N, Fs3, N],
  [D3, N, Fs3, N, A3, N, Fs3, N, A3, N, E3, N, A3, N, Cs4, N],
  [A3, N, E3, N, A3, N, G3, N, E3, N, Cs4, N, E3, N, G3, N],
  [D3, N, A3, N, D3, N, Fs3, N, B3, N, Fs3, N, B3, N, A3, N],
  [A3, N, E3, N, A3, N, Cs4, N, D3, N, A3, N, D3, N, Fs3, N],
  [G3, N, D3, N, G3, N, B3, N, A3, N, E3, N, A3, N, Cs4, N],
  [A3, N, E3, N, Cs4, N, E3, N, A3, N, G3, N, E3, N, A3, Cs4],
  [D3, N, N, N, A3, N, N, N, D3, N, N, N, F3, N, N, N],
  [Bb3, N, N, N, F3, N, N, N, A3, N, N, N, E3, N, Cs4, N],
  [D3, N, A3, N, Fs3, N, A3, N, D3, N, A3, N, D3, N, D3, N],
  [D3, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
)

// ---------------------------------------------------------------------------
// NOISE — one channel, one hit at a time, because the 2A03 noise channel
// cannot play two things at once. Silent three bars, a rope-snap pickup in
// bar 4, then the kit assembles a piece at a time. Bar 40 is empty so the
// roll's bell has the fourth voice to itself.
// ---------------------------------------------------------------------------
const CREDITS_NOISE: readonly CreditsDrumStep[] = phrase<CreditsDrumStep>(
  [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
  [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
  [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
  [N, N, N, N, N, N, N, N, N, N, N, N, 'r', N, 'h', 'h'],
  ['k', N, N, N, N, N, N, N, 'k', N, N, N, N, N, N, N],
  ['k', N, N, N, 's', N, N, N, 'k', N, N, N, N, N, N, 'r'],
  ['k', N, 'h', N, 's', N, N, N, 'k', N, 'h', N, 's', N, N, 'h'],
  ['k', N, 'h', N, 'S', N, 'h', N, 'k', N, 'h', N, 'S', N, 'h', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', N, 'K', N, 'h', N, 'S', N, 'h', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', 'k', 'K', N, 'h', N, 'S', N, 'h', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', N, 'K', N, 'h', 'k', 'S', N, 'h', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', N, 'K', N, 'S', N, 'S', 's', 'K', 'H'],
  ['k', N, 'h', N, 's', N, 'h', N, 'k', N, 'h', N, 's', N, 'h', 'h'],
  ['k', N, 'h', N, 's', N, 'h', N, 'k', N, 'h', 'k', 's', N, 'h', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', N, 'K', N, 'h', N, 'S', N, 'h', 'H'],
  ['K', N, 'h', 'k', 'S', N, 'h', N, 'K', N, 'h', N, 'S', N, 'h', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'h', 'h', 'K', 'h', 'h', 'h', 'S', 'h', 'h', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'k', 'h', 'K', 'h', 'h', 'h', 'S', 'h', 'h', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'h', 'h', 'K', 'h', 'K', 'h', 'S', 'h', 's', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'S', 'h', 'S', 's', 'S', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'h', 'h', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'k', 'h', 'K', 'h', 'K', 'h', 'S', 'h', 'h', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'h', 'k', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'K', 'h', 'S', 'h', 'h', 'h', 'K', 'h', 'S', 'h', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'h', 'h', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'K', 'h', 'S', 'h', 'k', 'h', 'K', 'h', 'h', 'h', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'S', 'h', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'K', 'h', 'S', 'h', 'K', 'h', 'S', 's', 'S', 's', 'S', 's', 'S', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', N, 'K', N, 'h', N, 'S', N, 'h', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', 'k', 'K', N, 'h', N, 'S', N, 'h', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', N, 'K', N, 'h', 'k', 'S', N, 'h', 'H'],
  ['K', N, 'h', N, 'S', N, 'h', N, 'K', N, 'S', N, 'S', 's', 'K', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'h', 'h', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'h', 'k', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'h', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'S', 'h', 'S', 'h', 'K', 'H'],
  ['K', 'h', 'K', 'h', 'S', 'h', 'K', 'h', 'S', 's', 'S', 's', 'S', 's', 'S', 'H'],
  ['k', N, N, N, N, N, N, N, 'h', N, N, N, 's', N, N, N],
  ['k', N, 'h', N, 's', N, 'h', N, 'K', N, 'S', N, 'S', 's', 'S', 's'],
  ['K', 'h', 'K', 'h', 'S', 'h', 'K', 'h', 'K', 'h', 'S', 'h', 'S', 's', 'S', 'H'],
  [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
)

// ---------------------------------------------------------------------------
// Arrangement blocks.
// ---------------------------------------------------------------------------
const CREDITS_SECTIONS: readonly CreditsSection[] = [
  {
    id: 'intro',
    label: 'Intro — D minor, under the title card',
    startBar: 0,
    bars: 4,
    pulse1: { duty: 0.125, gate: 3.6, attack: 0.02, sustain: 0.8, volume: 0.013 },
    pulse2: { duty: 0.25, gate: 8, attack: 0.03, sustain: 0.86, volume: 0.01 },
    triangle: { duty: 0, gate: 8, attack: 0.014, sustain: 0.84, volume: 0.034 },
  },
  {
    id: 'statement-a',
    label: 'A — first full statement of the credits theme',
    startBar: 4,
    bars: 8,
    pulse1: { duty: 0.5, gate: 3.6, attack: 0.008, sustain: 0.7, volume: 0.021 },
    pulse2: { duty: 0.25, gate: 4, attack: 0.008, sustain: 0.66, volume: 0.012 },
    triangle: { duty: 0, gate: 8, attack: 0.011, sustain: 0.8, volume: 0.038 },
  },
  {
    id: 'b-section',
    label: 'B — the lyrical turn, B-flat major',
    startBar: 12,
    bars: 8,
    pulse1: { duty: 0.125, gate: 1.6, attack: 0.004, sustain: 0.5, volume: 0.01 },
    pulse2: { duty: 0.25, gate: 1.8, attack: 0.005, sustain: 0.64, volume: 0.017 },
    triangle: { duty: 0, gate: 4.2, attack: 0.01, sustain: 0.8, volume: 0.037 },
  },
  {
    id: 'development',
    label: 'Development — F major, then the climb on A7',
    startBar: 20,
    bars: 8,
    pulse1: { duty: 0.5, gate: 1.7, attack: 0.005, sustain: 0.62, volume: 0.02 },
    pulse2: { duty: 0.25, gate: 1.6, attack: 0.004, sustain: 0.56, volume: 0.013 },
    triangle: { duty: 0, gate: 2.1, attack: 0.008, sustain: 0.76, volume: 0.038 },
  },
  {
    id: 'recap',
    label: 'Recap — the title-theme hook augmented in D major',
    startBar: 28,
    bars: 8,
    pulse1: { duty: 0.5, gate: 8.4, attack: 0.016, sustain: 0.9, volume: 0.023 },
    pulse2: { duty: 0.25, gate: 2, attack: 0.005, sustain: 0.62, volume: 0.014 },
    triangle: { duty: 0, gate: 2.1, attack: 0.008, sustain: 0.78, volume: 0.04 },
  },
  {
    id: 'coda',
    label: 'Coda — one last D minor, then D major and the bell',
    startBar: 36,
    bars: 4,
    pulse1: { duty: 0.5, gate: 4.2, attack: 0.01, sustain: 0.74, volume: 0.022 },
    pulse2: { duty: 0.25, gate: 4.2, attack: 0.01, sustain: 0.72, volume: 0.014 },
    triangle: { duty: 0, gate: 8, attack: 0.01, sustain: 0.84, volume: 0.042 },
  },
]

/** Landmarks a caller can sync the visual roll to. */
export const CREDITS_THEME_SECTIONS = [
  { id: 'intro', label: 'Intro — D minor, two voices', startBar: 1 },
  { id: 'statement-a', label: 'A — theme, first statement', startBar: 5 },
  { id: 'b-section', label: 'B — B-flat major, pulse 2 leads', startBar: 13 },
  { id: 'development', label: 'Development — F major', startBar: 21 },
  { id: 'dominant-climb', label: 'Dominant climb — A7 pedal', startBar: 27 },
  { id: 'recap', label: 'Recap — title hook augmented, D major', startBar: 29 },
  { id: 'recap-descant', label: 'Recap II — descant above the hook', startBar: 33 },
  { id: 'coda', label: 'Coda — the last D minor', startBar: 37 },
  { id: 'final-cadence', label: 'Final cadence — D major arpeggio', startBar: 39 },
  { id: 'bell', label: 'The bell', startBar: 40 },
].map((landmark) => ({
  ...landmark,
  startSeconds: (landmark.startBar - 1) * CREDITS_BAR_SECONDS,
}))

/**
 * Continuous dynamics, in [bar, level] breakpoints, smoothstep-interpolated
 * per note. The one steep move here is 36.85 -> 37.1: the composed subito
 * into the coda's D minor, not an artefact.
 */
const CREDITS_DYNAMICS: readonly (readonly [number, number])[] = [
  [0, 0.34], [4, 0.46], [8, 0.62], [12, 0.75], [13, 0.66], [17, 0.8],
  [20, 0.92], [21, 0.86], [25, 0.99], [28, 1.06], [29, 1.04], [33, 1.12],
  [36, 1.22], [36.85, 1.24], [37.1, 0.56], [38, 0.78], [39, 1.18],
  [40, 1.28], [41, 1.28],
]

/** Sixteenth-note accents, applied on top of the curve rather than instead. */
const CREDITS_ACCENTS: readonly number[] = [
  1.14, 0.92, 0.98, 0.95, 1.06, 0.92, 1, 0.96, 1.1, 0.93, 1, 0.95, 1.05, 0.94, 1, 1.04,
]

/**
 * Noise voices. `period` is a real 2A03 noise timer period — the LFSR clock
 * is 1789773 / period, so a long period rumbles and a short one hisses.
 * `rateFrom` sweeps playback rate, which is what the hardware does when a
 * program rewrites the period register mid-note. No filters are involved.
 */
const CREDITS_DRUMS: Record<Exclude<CreditsDrumStep, null>, {
  period: number
  volume: number
  decay: number
  rateFrom: number
}> = {
  K: { period: 4068, volume: 0.034, decay: 0.13, rateFrom: 1.95 },
  k: { period: 4068, volume: 0.022, decay: 0.1, rateFrom: 1.7 },
  S: { period: 254, volume: 0.026, decay: 0.11, rateFrom: 1.18 },
  s: { period: 254, volume: 0.015, decay: 0.075, rateFrom: 1.12 },
  H: { period: 128, volume: 0.013, decay: 0.075, rateFrom: 1 },
  h: { period: 128, volume: 0.0085, decay: 0.028, rateFrom: 1 },
  r: { period: 202, volume: 0.011, decay: 0.035, rateFrom: 1.4 },
}

/**
 * Where bar 40's downbeat sits — the D-major chord that ends the show and the
 * moment the roll's finale card is meant to lock up.
 *
 * The standalone deliverable pins the roll's duration to this and lets the
 * crawl speed float, so a longer contributor list runs faster rather than
 * running past the music. The in-app roll does not do that yet (credits.tsx
 * runs a fixed 40 px/s crawl and lets its duration float with content), so the
 * landmark is exported for it to adopt rather than assumed.
 */
export const CREDITS_THEME_BELL_SECONDS = CREDITS_FINAL_STEP * CREDITS_STEP_SECONDS

/** Music plus the final chord's ring-out. */
export const CREDITS_THEME_DURATION = CREDITS_DURATION

function creditsSmoothstep(t: number): number {
  return t * t * (3 - 2 * t)
}

function creditsDynamics(bar: number): number {
  if (bar <= CREDITS_DYNAMICS[0][0]) return CREDITS_DYNAMICS[0][1]
  for (let index = 1; index < CREDITS_DYNAMICS.length; index += 1) {
    const [barB, levelB] = CREDITS_DYNAMICS[index]
    if (bar <= barB) {
      const [barA, levelA] = CREDITS_DYNAMICS[index - 1]
      const span = barB - barA
      const t = span <= 0 ? 1 : creditsSmoothstep((bar - barA) / span)
      return levelA + (levelB - levelA) * t
    }
  }
  return CREDITS_DYNAMICS[CREDITS_DYNAMICS.length - 1][1]
}

function creditsSectionForBar(bar: number): CreditsSection {
  let found = CREDITS_SECTIONS[0]
  for (const section of CREDITS_SECTIONS) {
    if (bar >= section.startBar) found = section
  }
  return found
}

/**
 * Flatten one pitched channel into events, truncating every note at the next
 * onset in the SAME channel. An APU channel register write retriggers rather
 * than layering, so this is both authentic and what guarantees the four-voice
 * ceiling: four monophonic channels can never sound five things.
 */
function creditsPitchedEvents(
  steps: readonly CreditsNoteStep[],
  channel: CreditsPitchedChannel,
): CreditsEvent[] {
  const onsets: number[] = []
  for (let step = 0; step < steps.length; step += 1) {
    if (steps[step] !== null && steps[step] !== undefined) onsets.push(step)
  }
  return onsets.map((step, index) => {
    const bar = step / CREDITS_STEPS_PER_BAR
    const voice = creditsSectionForBar(Math.floor(bar))[channel]
    const next = onsets[index + 1]
    const untilNext = next === undefined
      ? Number.POSITIVE_INFINITY
      : (next - step) * CREDITS_STEP_SECONDS
    const duration = step === CREDITS_FINAL_STEP
      ? CREDITS_DURATION - step * CREDITS_STEP_SECONDS
      : Math.min(voice.gate * CREDITS_STEP_SECONDS, untilNext)
    return {
      channel,
      kind: 'note' as const,
      time: step * CREDITS_STEP_SECONDS,
      duration,
      gain: voice.volume
        * CREDITS_ACCENTS[step % CREDITS_STEPS_PER_BAR]
        * creditsDynamics(bar),
      frequency: steps[step] as number,
      duty: voice.duty,
      attack: voice.attack,
      sustain: voice.sustain,
    }
  })
}

function creditsNoiseEvents(steps: readonly CreditsDrumStep[]): CreditsEvent[] {
  const events: CreditsEvent[] = []
  for (let step = 0; step < steps.length; step += 1) {
    const token = steps[step]
    if (!token) continue
    const drum = CREDITS_DRUMS[token]
    const bar = step / CREDITS_STEPS_PER_BAR
    let next = step + 1
    while (next < steps.length && !steps[next]) next += 1
    const untilNext = next >= steps.length
      ? Number.POSITIVE_INFINITY
      : (next - step) * CREDITS_STEP_SECONDS
    events.push({
      channel: 'noise',
      kind: 'noise',
      time: step * CREDITS_STEP_SECONDS,
      duration: Math.min(drum.decay, untilNext),
      gain: drum.volume * Math.min(1.12, creditsDynamics(bar)),
      period: drum.period,
      rateFrom: drum.rateFrom,
    })
  }
  return events
}

let cached: CreditsPlan | null = null

/**
 * The whole cue as one event list.
 *
 * It is through-composed and ENDS: everything goes in introEvents and
 * loopEvents is empty, which is how the shared runtime is told a cue plays
 * once. Built on first call and reused, since the plan is a pure function of
 * the score.
 */
export function creditsCuePlan(): CreditsPlan {
  if (cached) return cached
  const events: readonly CreditsEvent[] = [
    ...creditsPitchedEvents(CREDITS_PULSE_1, 'pulse1'),
    ...creditsPitchedEvents(CREDITS_PULSE_2, 'pulse2'),
    ...creditsPitchedEvents(CREDITS_TRIANGLE, 'triangle'),
    ...creditsNoiseEvents(CREDITS_NOISE),
  ].sort((a, b) => a.time - b.time)
  cached = {
    introDuration: CREDITS_DURATION,
    loopDuration: 0,
    introEvents: events,
    loopEvents: [],
    bellTime: CREDITS_THEME_BELL_SECONDS,
  }
  return cached
}
